# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NTLoggerTool_ui.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wWindow(object):
    WINSCALE = 1.0

    def SCALE(self, scale):
        if( scale>=16777215 ): return scale
        return int(self.WINSCALE*scale)

    def setupUi(self, wWindow, winScale):
        self.WINSCALE = winScale

        wWindow.setObjectName("wWindow")
        wWindow.resize(self.SCALE(800), self.SCALE(640))
        wWindow.setMinimumSize(QtCore.QSize(self.SCALE(660), self.SCALE(300)))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resources/owdefault.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        wWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(wWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(self.SCALE(250), self.SCALE(180)))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setContentsMargins(self.SCALE(-1), self.SCALE(-1), self.SCALE(-1), self.SCALE(3))
        self.topLayout.setObjectName("topLayout")
        self.bLoad = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLoad.sizePolicy().hasHeightForWidth())
        self.bLoad.setSizePolicy(sizePolicy)
        self.bLoad.setMinimumSize(QtCore.QSize(self.SCALE(65), 0))
        self.bLoad.setMaximumSize(QtCore.QSize(self.SCALE(65), 16777215))
        self.bLoad.setObjectName("bLoad")
        self.topLayout.addWidget(self.bLoad)
        self.bSave = QtWidgets.QPushButton(self.centralwidget)
        self.bSave.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bSave.sizePolicy().hasHeightForWidth())
        self.bSave.setSizePolicy(sizePolicy)
        self.bSave.setMinimumSize(QtCore.QSize(self.SCALE(65), 0))
        self.bSave.setMaximumSize(QtCore.QSize(self.SCALE(65), 16777215))
        self.bSave.setObjectName("bSave")
        self.topLayout.addWidget(self.bSave)
        self.bCancelLoad = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bCancelLoad.sizePolicy().hasHeightForWidth())
        self.bCancelLoad.setSizePolicy(sizePolicy)
        self.bCancelLoad.setMinimumSize(QtCore.QSize(self.SCALE(65), 0))
        self.bCancelLoad.setMaximumSize(QtCore.QSize(self.SCALE(65), 16777215))
        self.bCancelLoad.setObjectName("bCancelLoad")
        self.topLayout.addWidget(self.bCancelLoad)
        self.wProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.wProgressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wProgressBar.sizePolicy().hasHeightForWidth())
        self.wProgressBar.setSizePolicy(sizePolicy)
        self.wProgressBar.setMinimumSize(QtCore.QSize(0, self.SCALE(19)))
        self.wProgressBar.setMaximumSize(QtCore.QSize(self.SCALE(100), self.SCALE(19)))
        self.wProgressBar.setProperty("value", 0)
        self.wProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.wProgressBar.setTextVisible(True)
        self.wProgressBar.setObjectName("wProgressBar")
        self.topLayout.addWidget(self.wProgressBar)
        spacerItem = QtWidgets.QSpacerItem(self.SCALE(5), self.SCALE(20), QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topLayout.addItem(spacerItem)
        self.wLogFileName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wLogFileName.sizePolicy().hasHeightForWidth())
        self.wLogFileName.setSizePolicy(sizePolicy)
        self.wLogFileName.setText("")
        self.wLogFileName.setObjectName("wLogFileName")
        self.topLayout.addWidget(self.wLogFileName)
        self.wGraphFftLength = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphFftLength.sizePolicy().hasHeightForWidth())
        self.wGraphFftLength.setSizePolicy(sizePolicy)
        self.wGraphFftLength.setMinimumSize(QtCore.QSize(self.SCALE(75), self.SCALE(21)))
        self.wGraphFftLength.setMaximumSize(QtCore.QSize(self.SCALE(75), self.SCALE(21)))
        self.wGraphFftLength.setObjectName("wGraphFftLength")
        self.topLayout.addWidget(self.wGraphFftLength)
        self.wGraphFftWindow = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphFftWindow.sizePolicy().hasHeightForWidth())
        self.wGraphFftWindow.setSizePolicy(sizePolicy)
        self.wGraphFftWindow.setMinimumSize(QtCore.QSize(self.SCALE(75), self.SCALE(21)))
        self.wGraphFftWindow.setMaximumSize(QtCore.QSize(self.SCALE(75), self.SCALE(21)))
        self.wGraphFftWindow.setObjectName("wGraphFftWindow")
        self.topLayout.addWidget(self.wGraphFftWindow)
        self.wGraphFftOutput = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphFftOutput.sizePolicy().hasHeightForWidth())
        self.wGraphFftOutput.setSizePolicy(sizePolicy)
        self.wGraphFftOutput.setMinimumSize(QtCore.QSize(self.SCALE(75), self.SCALE(21)))
        self.wGraphFftOutput.setMaximumSize(QtCore.QSize(self.SCALE(75), self.SCALE(21)))
        self.wGraphFftOutput.setObjectName("wGraphFftOutput")
        self.topLayout.addWidget(self.wGraphFftOutput)
        self.wGraphFftPreFilter = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphFftPreFilter.sizePolicy().hasHeightForWidth())
        self.wGraphFftPreFilter.setSizePolicy(sizePolicy)
        self.wGraphFftPreFilter.setMinimumSize(QtCore.QSize(self.SCALE(75), self.SCALE(21)))
        self.wGraphFftPreFilter.setMaximumSize(QtCore.QSize(self.SCALE(75), self.SCALE(21)))
        self.wGraphFftPreFilter.setObjectName("wGraphFftPreFilter")
        self.topLayout.addWidget(self.wGraphFftPreFilter)
        self.bRecordStartStop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bRecordStartStop.sizePolicy().hasHeightForWidth())
        self.bRecordStartStop.setSizePolicy(sizePolicy)
        self.bRecordStartStop.setMinimumSize(QtCore.QSize(self.SCALE(65), 0))
        self.bRecordStartStop.setMaximumSize(QtCore.QSize(self.SCALE(65), 16777215))
        self.bRecordStartStop.setCheckable(True)
        self.bRecordStartStop.setObjectName("bRecordStartStop")
        self.topLayout.addWidget(self.bRecordStartStop)
        self.bRecordClear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bRecordClear.sizePolicy().hasHeightForWidth())
        self.bRecordClear.setSizePolicy(sizePolicy)
        self.bRecordClear.setMinimumSize(QtCore.QSize(self.SCALE(65), 0))
        self.bRecordClear.setMaximumSize(QtCore.QSize(self.SCALE(65), 16777215))
        self.bRecordClear.setObjectName("bRecordClear")
        self.topLayout.addWidget(self.bRecordClear)
        self.verticalLayout_3.addLayout(self.topLayout)
        self.wTab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wTab.setFont(font)
        self.wTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.wTab.setObjectName("wTab")
        self.wTraffic = QtWidgets.QWidget()
        self.wTraffic.setObjectName("wTraffic")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wTraffic)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bLoadTraffic = QtWidgets.QCheckBox(self.wTraffic)
        self.bLoadTraffic.setObjectName("bLoadTraffic")
        self.verticalLayout.addWidget(self.bLoadTraffic)
        self.wTrafficText = QtWidgets.QPlainTextEdit(self.wTraffic)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.wTrafficText.setFont(font)
        self.wTrafficText.setAcceptDrops(False)
        self.wTrafficText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wTrafficText.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wTrafficText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.wTrafficText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.wTrafficText.setUndoRedoEnabled(False)
        self.wTrafficText.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.wTrafficText.setReadOnly(True)
        self.wTrafficText.setCursorWidth(1)
        self.wTrafficText.setObjectName("wTrafficText")
        self.verticalLayout.addWidget(self.wTrafficText)
        self.wTab.addTab(self.wTraffic, "")
        self.wData = QtWidgets.QWidget()
        self.wData.setObjectName("wData")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wData)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wDataText = QtWidgets.QPlainTextEdit(self.wData)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(10)
        self.wDataText.setFont(font)
        self.wDataText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.wDataText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.wDataText.setUndoRedoEnabled(False)
        self.wDataText.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.wDataText.setReadOnly(True)
        self.wDataText.setObjectName("wDataText")
        self.verticalLayout_2.addWidget(self.wDataText)
        self.wTab.addTab(self.wData, "")
        self.wGraphic = QtWidgets.QWidget()
        self.wGraphic.setObjectName("wGraphic")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wGraphic)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(self.SCALE(2))
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wGraphCentralWidget = QtWidgets.QWidget(self.wGraphic)
        self.wGraphCentralWidget.setObjectName("wGraphCentralWidget")
        self.wGraphCentralWidgetLayout = QtWidgets.QVBoxLayout(self.wGraphCentralWidget)
        self.wGraphCentralWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.wGraphCentralWidgetLayout.setSpacing(0)
        self.wGraphCentralWidgetLayout.setObjectName("wGraphCentralWidgetLayout")
        self.wGraphAreaWidget = QtWidgets.QWidget(self.wGraphCentralWidget)
        self.wGraphAreaWidget.setObjectName("wGraphAreaWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.wGraphAreaWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget = QtWidgets.QWidget(self.wGraphAreaWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(self.SCALE(6), self.SCALE(3), self.SCALE(6), self.SCALE(3))
        self.verticalLayout_4.setSpacing(self.SCALE(6))
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wGraphLegend = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphLegend.sizePolicy().hasHeightForWidth())
        self.wGraphLegend.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.wGraphLegend.setFont(font)
        self.wGraphLegend.setAutoFillBackground(False)
        self.wGraphLegend.setText("textlabel")
        self.wGraphLegend.setWordWrap(True)
        self.wGraphLegend.setObjectName("wGraphLegend")
        self.verticalLayout_4.addWidget(self.wGraphLegend)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.wGraphCursor = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphCursor.sizePolicy().hasHeightForWidth())
        self.wGraphCursor.setSizePolicy(sizePolicy)
        self.wGraphCursor.setMinimumSize(QtCore.QSize(self.SCALE(160), 0))
        self.wGraphCursor.setMaximumSize(QtCore.QSize(self.SCALE(160), 16777215))
        self.wGraphCursor.setObjectName("wGraphCursor")
        self.horizontalLayout_4.addWidget(self.wGraphCursor)
        spacerItem1 = QtWidgets.QSpacerItem(self.SCALE(40), self.SCALE(20), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.wGraphTimeLabel = QtWidgets.QLabel(self.widget)
        self.wGraphTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wGraphTimeLabel.setObjectName("wGraphTimeLabel")
        self.horizontalLayout_4.addWidget(self.wGraphTimeLabel)
        spacerItem2 = QtWidgets.QSpacerItem(self.SCALE(40), self.SCALE(20), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(self.SCALE(85), self.SCALE(20), QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.wGraphMaxTimeLabel = QtWidgets.QLabel(self.widget)
        self.wGraphMaxTimeLabel.setObjectName("wGraphMaxTimeLabel")
        self.horizontalLayout_4.addWidget(self.wGraphMaxTimeLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addWidget(self.widget)
        self.wGraphPlotArea = QtWidgets.QWidget(self.wGraphAreaWidget)
        self.wGraphPlotArea.setObjectName("wGraphPlotArea")
        self.wGraphAreaLayout = QtWidgets.QVBoxLayout(self.wGraphPlotArea)
        self.wGraphAreaLayout.setContentsMargins(0, 0, 0, 0)
        self.wGraphAreaLayout.setSpacing(0)
        self.wGraphAreaLayout.setObjectName("wGraphAreaLayout")
        self.verticalLayout_9.addWidget(self.wGraphPlotArea)
        self.wGraphComment = QtWidgets.QLabel(self.wGraphAreaWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphComment.sizePolicy().hasHeightForWidth())
        self.wGraphComment.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 160, 160))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.wGraphComment.setPalette(palette)
        self.wGraphComment.setAutoFillBackground(True)
        self.wGraphComment.setText("TextLabel")
        self.wGraphComment.setWordWrap(True)
        self.wGraphComment.setObjectName("wGraphComment")
        self.verticalLayout_9.addWidget(self.wGraphComment)
        self.wGraphCentralWidgetLayout.addWidget(self.wGraphAreaWidget)
        self.widget_2 = QtWidgets.QWidget(self.wGraphCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(self.SCALE(6), self.SCALE(3), self.SCALE(6), 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wGraphTimeSlider = QtWidgets.QSlider(self.widget_2)
        self.wGraphTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.wGraphTimeSlider.setObjectName("wGraphTimeSlider")
        self.horizontalLayout_2.addWidget(self.wGraphTimeSlider)
        self.wGraphCentralWidgetLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.wGraphCentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(self.SCALE(6), self.SCALE(3), self.SCALE(6), self.SCALE(3))
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bScreenShot = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bScreenShot.sizePolicy().hasHeightForWidth())
        self.bScreenShot.setSizePolicy(sizePolicy)
        self.bScreenShot.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bScreenShot.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.bScreenShot.setFont(font)
        self.bScreenShot.setObjectName("bScreenShot")
        self.horizontalLayout_3.addWidget(self.bScreenShot)
        spacerItem4 = QtWidgets.QSpacerItem(self.SCALE(10), self.SCALE(20), QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(self.SCALE(-1), self.SCALE(-1), 0, self.SCALE(-1))
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bPlaybackBegin = QtWidgets.QPushButton(self.widget_3)
        self.bPlaybackBegin.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPlaybackBegin.sizePolicy().hasHeightForWidth())
        self.bPlaybackBegin.setSizePolicy(sizePolicy)
        self.bPlaybackBegin.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bPlaybackBegin.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bPlaybackBegin.setText("")
        self.bPlaybackBegin.setObjectName("bPlaybackBegin")
        self.horizontalLayout_7.addWidget(self.bPlaybackBegin)
        self.bPlaybackSkipBackward = QtWidgets.QPushButton(self.widget_3)
        self.bPlaybackSkipBackward.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPlaybackSkipBackward.sizePolicy().hasHeightForWidth())
        self.bPlaybackSkipBackward.setSizePolicy(sizePolicy)
        self.bPlaybackSkipBackward.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bPlaybackSkipBackward.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bPlaybackSkipBackward.setText("")
        self.bPlaybackSkipBackward.setObjectName("bPlaybackSkipBackward")
        self.horizontalLayout_7.addWidget(self.bPlaybackSkipBackward)
        self.bPlaybackPlayStop = QtWidgets.QPushButton(self.widget_3)
        self.bPlaybackPlayStop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPlaybackPlayStop.sizePolicy().hasHeightForWidth())
        self.bPlaybackPlayStop.setSizePolicy(sizePolicy)
        self.bPlaybackPlayStop.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bPlaybackPlayStop.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bPlaybackPlayStop.setText("")
        self.bPlaybackPlayStop.setObjectName("bPlaybackPlayStop")
        self.horizontalLayout_7.addWidget(self.bPlaybackPlayStop)
        self.bPlaybackSkipForward = QtWidgets.QPushButton(self.widget_3)
        self.bPlaybackSkipForward.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPlaybackSkipForward.sizePolicy().hasHeightForWidth())
        self.bPlaybackSkipForward.setSizePolicy(sizePolicy)
        self.bPlaybackSkipForward.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bPlaybackSkipForward.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bPlaybackSkipForward.setText("")
        self.bPlaybackSkipForward.setObjectName("bPlaybackSkipForward")
        self.horizontalLayout_7.addWidget(self.bPlaybackSkipForward)
        self.bPlaybackEnd = QtWidgets.QPushButton(self.widget_3)
        self.bPlaybackEnd.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bPlaybackEnd.sizePolicy().hasHeightForWidth())
        self.bPlaybackEnd.setSizePolicy(sizePolicy)
        self.bPlaybackEnd.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bPlaybackEnd.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bPlaybackEnd.setText("")
        self.bPlaybackEnd.setObjectName("bPlaybackEnd")
        self.horizontalLayout_7.addWidget(self.bPlaybackEnd)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_7)
        self.wPlaybackSpeedFactorLabel = QtWidgets.QLabel(self.widget_3)
        self.wPlaybackSpeedFactorLabel.setObjectName("wPlaybackSpeedFactorLabel")
        self.horizontalLayout_3.addWidget(self.wPlaybackSpeedFactorLabel)
        self.wPlaybackSpeedFactor = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wPlaybackSpeedFactor.sizePolicy().hasHeightForWidth())
        self.wPlaybackSpeedFactor.setSizePolicy(sizePolicy)
        self.wPlaybackSpeedFactor.setMinimumSize(QtCore.QSize(self.SCALE(50), self.SCALE(21)))
        self.wPlaybackSpeedFactor.setMaximumSize(QtCore.QSize(self.SCALE(50), self.SCALE(21)))
        self.wPlaybackSpeedFactor.setObjectName("wPlaybackSpeedFactor")
        self.horizontalLayout_3.addWidget(self.wPlaybackSpeedFactor)
        spacerItem5 = QtWidgets.QSpacerItem(self.SCALE(40), self.SCALE(20), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.bGraphZoom = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bGraphZoom.sizePolicy().hasHeightForWidth())
        self.bGraphZoom.setSizePolicy(sizePolicy)
        self.bGraphZoom.setMinimumSize(QtCore.QSize(self.SCALE(65), 0))
        self.bGraphZoom.setMaximumSize(QtCore.QSize(self.SCALE(65), 16777215))
        self.bGraphZoom.setObjectName("bGraphZoom")
        self.horizontalLayout_3.addWidget(self.bGraphZoom)
        self.wGraphZoomFactor = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphZoomFactor.sizePolicy().hasHeightForWidth())
        self.wGraphZoomFactor.setSizePolicy(sizePolicy)
        self.wGraphZoomFactor.setMinimumSize(QtCore.QSize(self.SCALE(65), self.SCALE(21)))
        self.wGraphZoomFactor.setMaximumSize(QtCore.QSize(self.SCALE(65), self.SCALE(21)))
        self.wGraphZoomFactor.setObjectName("wGraphZoomFactor")
        self.horizontalLayout_3.addWidget(self.wGraphZoomFactor)
        spacerItem6 = QtWidgets.QSpacerItem(self.SCALE(40), self.SCALE(20), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(self.SCALE(-1), self.SCALE(-1), 0, self.SCALE(-1))
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bAutoRangeAll = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bAutoRangeAll.sizePolicy().hasHeightForWidth())
        self.bAutoRangeAll.setSizePolicy(sizePolicy)
        self.bAutoRangeAll.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bAutoRangeAll.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bAutoRangeAll.setObjectName("bAutoRangeAll")
        self.horizontalLayout_8.addWidget(self.bAutoRangeAll)
        self.bXAutoRange = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bXAutoRange.sizePolicy().hasHeightForWidth())
        self.bXAutoRange.setSizePolicy(sizePolicy)
        self.bXAutoRange.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bXAutoRange.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bXAutoRange.setObjectName("bXAutoRange")
        self.horizontalLayout_8.addWidget(self.bXAutoRange)
        self.bYAutoRangeFull = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bYAutoRangeFull.sizePolicy().hasHeightForWidth())
        self.bYAutoRangeFull.setSizePolicy(sizePolicy)
        self.bYAutoRangeFull.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bYAutoRangeFull.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bYAutoRangeFull.setObjectName("bYAutoRangeFull")
        self.horizontalLayout_8.addWidget(self.bYAutoRangeFull)
        self.bYAutoRangeView = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bYAutoRangeView.sizePolicy().hasHeightForWidth())
        self.bYAutoRangeView.setSizePolicy(sizePolicy)
        self.bYAutoRangeView.setMinimumSize(QtCore.QSize(self.SCALE(23), 0))
        self.bYAutoRangeView.setMaximumSize(QtCore.QSize(self.SCALE(23), 16777215))
        self.bYAutoRangeView.setObjectName("bYAutoRangeView")
        self.horizontalLayout_8.addWidget(self.bYAutoRangeView)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_8)
        self.wGraphCentralWidgetLayout.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.wGraphCentralWidget)
        self.wGraphSelectorWidget = QtWidgets.QWidget(self.wGraphic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wGraphSelectorWidget.sizePolicy().hasHeightForWidth())
        self.wGraphSelectorWidget.setSizePolicy(sizePolicy)
        self.wGraphSelectorWidget.setMinimumSize(QtCore.QSize(self.SCALE(170), 0))
        self.wGraphSelectorWidget.setMaximumSize(QtCore.QSize(self.SCALE(165), 16777215))
        self.wGraphSelectorWidget.setObjectName("wGraphSelectorWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.wGraphSelectorWidget)
        self.verticalLayout_5.setContentsMargins(0, self.SCALE(6), 0, self.SCALE(1))
        self.verticalLayout_5.setSpacing(self.SCALE(6))
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bGraphSelectorClear = QtWidgets.QPushButton(self.wGraphSelectorWidget)
        self.bGraphSelectorClear.setObjectName("bGraphSelectorClear")
        self.verticalLayout_5.addWidget(self.bGraphSelectorClear)
        self.wGraphSelectorTree = QtWidgets.QTreeWidget(self.wGraphSelectorWidget)
        self.wGraphSelectorTree.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.wGraphSelectorTree.setIndentation(10)
        self.wGraphSelectorTree.setUniformRowHeights(True)
        self.wGraphSelectorTree.setHeaderHidden(True)
        self.wGraphSelectorTree.setObjectName("wGraphSelectorTree")
        self.wGraphSelectorTree.headerItem().setText(0, "1")
        self.verticalLayout_5.addWidget(self.wGraphSelectorTree)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(self.SCALE(2), self.SCALE(20), QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.bGraphShowFft = QtWidgets.QCheckBox(self.wGraphSelectorWidget)
        self.bGraphShowFft.setObjectName("bGraphShowFft")
        self.horizontalLayout_5.addWidget(self.bGraphShowFft)
        spacerItem8 = QtWidgets.QSpacerItem(self.SCALE(10), self.SCALE(20), QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.bFftAutoRange = QtWidgets.QCheckBox(self.wGraphSelectorWidget)
        self.bFftAutoRange.setChecked(True)
        self.bFftAutoRange.setObjectName("bFftAutoRange")
        self.horizontalLayout_5.addWidget(self.bFftAutoRange)
        spacerItem9 = QtWidgets.QSpacerItem(self.SCALE(40), self.SCALE(20), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.bGraphShowRecord = QtWidgets.QCheckBox(self.wGraphSelectorWidget)
        self.bGraphShowRecord.setObjectName("bGraphShowRecord")
        self.horizontalLayout_5.addWidget(self.bGraphShowRecord)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem10 = QtWidgets.QSpacerItem(self.SCALE(2), self.SCALE(20), QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.bYAutoRangeOff = QtWidgets.QCheckBox(self.wGraphSelectorWidget)
        self.bYAutoRangeOff.setObjectName("bYAutoRangeOff")
        self.horizontalLayout_6.addWidget(self.bYAutoRangeOff)
        spacerItem11 = QtWidgets.QSpacerItem(self.SCALE(10), self.SCALE(20), QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.bGraphShowPoints = QtWidgets.QCheckBox(self.wGraphSelectorWidget)
        self.bGraphShowPoints.setObjectName("bGraphShowPoints")
        self.horizontalLayout_6.addWidget(self.bGraphShowPoints)
        spacerItem12 = QtWidgets.QSpacerItem(self.SCALE(40), self.SCALE(20), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout.addWidget(self.wGraphSelectorWidget)
        self.wTab.addTab(self.wGraphic, "")
        self.verticalLayout_3.addWidget(self.wTab)
        wWindow.setCentralWidget(self.centralwidget)
        self.wMenu = QtWidgets.QMenuBar(wWindow)
        self.wMenu.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.wMenu.setObjectName("wMenu")
        self.mFile = QtWidgets.QMenu(self.wMenu)
        self.mFile.setObjectName("mFile")
        self.menu = QtWidgets.QMenu(self.wMenu)
        self.menu.setObjectName("menu")
        wWindow.setMenuBar(self.wMenu)
        self.actionLoad = QtWidgets.QAction(wWindow)
        icon = QtGui.QIcon.fromTheme("window-new")
        self.actionLoad.setIcon(icon)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(wWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(wWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExit = QtWidgets.QAction(wWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(wWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClear = QtWidgets.QAction(wWindow)
        self.actionClear.setEnabled(False)
        self.actionClear.setObjectName("actionClear")
        self.mFile.addAction(self.actionLoad)
        self.mFile.addAction(self.actionSave)
        self.mFile.addAction(self.actionClear)
        self.mFile.addSeparator()
        self.mFile.addAction(self.actionExit)
        self.menu.addAction(self.actionAbout)
        self.wMenu.addAction(self.mFile.menuAction())
        self.wMenu.addAction(self.menu.menuAction())

        self.retranslateUi(wWindow)
        self.wTab.setCurrentIndex(2)
        self.actionLoad.triggered.connect(wWindow.loadLogFile)
        self.actionSave.triggered.connect(wWindow.saveDataIntoFile)
        self.actionExit.triggered.connect(wWindow.close)
        self.bLoad.clicked.connect(wWindow.loadLogFile)
        self.bSave.clicked.connect(wWindow.saveDataIntoFile)
        self.bCancelLoad.clicked.connect(wWindow.loadLogFileCancel)
        self.actionAbout.triggered.connect(wWindow.openAbout)
        self.actionClear.triggered.connect(wWindow.clearLogFile)
        self.bGraphZoom.clicked.connect(wWindow.doGraphZoomFactor)
        QtCore.QMetaObject.connectSlotsByName(wWindow)
        wWindow.setTabOrder(self.wTab, self.wTrafficText)

    def retranslateUi(self, wWindow):
        _translate = QtCore.QCoreApplication.translate
        wWindow.setWindowTitle(_translate("wWindow", "NT DataLogger Tool"))
        self.bLoad.setText(_translate("wWindow", " Load"))
        self.bSave.setText(_translate("wWindow", " Save"))
        self.bCancelLoad.setText(_translate("wWindow", "Cancel"))
        self.wGraphFftLength.setToolTip(_translate("wWindow", "FFT Window Length"))
        self.wGraphFftWindow.setToolTip(_translate("wWindow", "FFT Windowing Function"))
        self.wGraphFftOutput.setToolTip(_translate("wWindow", "FFT Output"))
        self.wGraphFftPreFilter.setToolTip(_translate("wWindow", "FFT Prefilter"))
        self.bRecordStartStop.setText(_translate("wWindow", "Rec Start"))
        self.bRecordClear.setText(_translate("wWindow", "Clear"))
        self.bLoadTraffic.setText(_translate("wWindow", "load complete traffic"))
        self.wTab.setTabText(self.wTab.indexOf(self.wTraffic), _translate("wWindow", "Traffic"))
        self.wTab.setTabText(self.wTab.indexOf(self.wData), _translate("wWindow", "Data"))
        self.wGraphCursor.setText(_translate("wWindow", "TextLabel"))
        self.wGraphTimeLabel.setText(_translate("wWindow", "TextLabel"))
        self.wGraphMaxTimeLabel.setText(_translate("wWindow", "TextLabel"))
        self.bScreenShot.setToolTip(_translate("wWindow", "ScreenShot\n"
"Takes and saves a screen shot"))
        self.bScreenShot.setText(_translate("wWindow", "O"))
        self.wPlaybackSpeedFactorLabel.setText(_translate("wWindow", "Speed"))
        self.bGraphZoom.setToolTip(_translate("wWindow", "Zoom\n"
"Applies the selected zoom range to the x axis"))
        self.bGraphZoom.setText(_translate("wWindow", "Zoom"))
        self.wGraphZoomFactor.setToolTip(_translate("wWindow", "Zoom Range\n"
"Range of the x axis"))
        self.bAutoRangeAll.setToolTip(_translate("wWindow", "AutoScale\n"
"Plot x-y axes are set to maximum ranges"))
        self.bAutoRangeAll.setText(_translate("wWindow", "A"))
        self.bXAutoRange.setToolTip(_translate("wWindow", "AutoScale X Axis\n"
"Plot x axis is set to maximum range"))
        self.bXAutoRange.setText(_translate("wWindow", "xA"))
        self.bYAutoRangeFull.setToolTip(_translate("wWindow", "AutoScale Y Axis\n"
"Plot y axis is set to maximum range"))
        self.bYAutoRangeFull.setText(_translate("wWindow", "yA"))
        self.bYAutoRangeView.setToolTip(_translate("wWindow", "AutoScale Plot Y Axis\n"
"Plot y axis is set to maximum in visible range"))
        self.bYAutoRangeView.setText(_translate("wWindow", "yP"))
        self.bGraphSelectorClear.setText(_translate("wWindow", "Clear All Selections"))
        self.bGraphShowFft.setToolTip(_translate("wWindow", "FFT Plot\n"
"Shows the FFT plot"))
        self.bGraphShowFft.setText(_translate("wWindow", "fft"))
        self.bFftAutoRange.setToolTip(_translate("wWindow", "FFT Plot\n"
"Enables FFT plot autoranging"))
        self.bFftAutoRange.setText(_translate("wWindow", "fft AR"))
        self.bGraphShowRecord.setToolTip(_translate("wWindow", "Live Recording\n"
"Enables the live recording feature"))
        self.bGraphShowRecord.setText(_translate("wWindow", "rec"))
        self.bYAutoRangeOff.setToolTip(_translate("wWindow", "Y Auto Ranging\n"
"Disables autoranging of the y axis"))
        self.bYAutoRangeOff.setText(_translate("wWindow", "y-AR off"))
        self.bGraphShowPoints.setToolTip(_translate("wWindow", "Show Data Points\n"
"Enables showing data points"))
        self.bGraphShowPoints.setText(_translate("wWindow", "show points"))
        self.wTab.setTabText(self.wTab.indexOf(self.wGraphic), _translate("wWindow", "Graph"))
        self.mFile.setTitle(_translate("wWindow", "File"))
        self.menu.setTitle(_translate("wWindow", "?"))
        self.actionLoad.setText(_translate("wWindow", "Load ..."))
        self.actionSave.setText(_translate("wWindow", "Save ..."))
        self.actionSave_as.setText(_translate("wWindow", "Save as ..."))
        self.actionExit.setText(_translate("wWindow", "Exit"))
        self.actionAbout.setText(_translate("wWindow", "About ..."))
        self.actionClear.setText(_translate("wWindow", "Clear"))

import NTLoggerTool_qrc_rc
